### PR TITLE
fix: Make appWithTranslation generic over AppProps type

### LINKED ISSUE #1348: Types missmatching with custom Application
## Describe the bug
We made a custom `App` for our website as follows:
```typescript
const clientSideEmotionCache = createEmotionCache();

export function reportWebVitals(metric: NextWebVitalsMetric): void {
  if (process.env.NODE_ENV === "development") console.log(metric);
}

interface Props extends AppProps {
  // title: string;
  navLinks: INavLink[];
  emotionCache?: EmotionCache;
}

const FolioApp = ({
  Component,
  pageProps,
  navLinks,
  emotionCache = clientSideEmotionCache,
}: Props) => {
  return (
    <CacheProvider value={emotionCache}>
      <Meta />
      <ThemeProvider theme={theme}>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline />
        <Nav navLinks={navLinks} />
        <Component {...pageProps} />
        <Footer navLinks={navLinks} />
      </ThemeProvider>
    </CacheProvider>
  );
};

FolioApp.getInitialProps = async (appContext: AppContext) => {
  const appProps = await App.getInitialProps(appContext);

  const navLinks: INavLink[] = [];
  /*await getPageTitlesBySlugSet(
    menuLinks.map(({ label }: IMenuLink) => label)
  );*/

  return { ...appProps, navLinks };
};

export default appWithTranslation(FolioApp);
```

This code gives us a type error at `appWithTranslation`:
```shell
<html>TS2345: Argument of type '{ ({ Component, pageProps, navLinks }: Props): JSX.Element; getInitialProps(appContext: AppContext): Promise&lt;{ navLinks: INavLink[]; pageProps: any; }&gt;; }' is not assignable to parameter of type 'ComponentClass&lt;AppProps, any&gt; | FunctionComponent&lt;AppProps&gt;'.<br/>Type '{ ({ Component, pageProps, navLinks }: Props): JSX.Element; getInitialProps(appContext: AppContext): Promise&lt;{ navLinks: INavLink[]; pageProps: any; }&gt;; }' is not assignable to type 'FunctionComponent&lt;AppProps&gt;'.<br/>Types of parameters '__0' and 'props' are incompatible.<br/>Property 'navLinks' is missing in type 'PropsWithChildren&lt;AppProps&gt;' but required in type 'Props'.
```

## Occurs in next-i18next version
Setup:
```json

    "next": "11.0.1",
    "next-compose-plugins": "^2.2.1",
    "next-i18next": "^8.5.5",
    "next-offline": "^5.0.5",
    "next-seo": "^4.26.0",
    "next-unused": "^0.0.6",

```

## Steps to reproduce

1. Write the code above on the IDE/Text Editor.
2. Look at lint analyser results.

## Expected behaviour
It should not be a type error.

## Screenshots
image

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: Chrome 92

### PR DESCRIPTION
**Pull request by petarvujovic98**
Add support for proper custom App component types
fix #1348

### CODE REVIEW

**Comment by petarvujovic98** [comment]
Closes #1348

File: src/appWithTranslation.tsx [hunk 1]
```diff
@@ -17,11 +17,11 @@ type AppProps = NextJsAppProps & {
 
 export let globalI18n: I18NextClient | null = null
 
-export const appWithTranslation = (
-  WrappedComponent: React.ComponentType<AppProps> | React.ElementType<AppProps>,
+export const appWithTranslation = <Props extends AppProps = AppProps>(
+  WrappedComponent: React.ComponentType<Props> | React.ElementType<AppProps>,
```
Comment (isaachinman) [inline src/appWithTranslation.tsx:21]:
```suggestion
  WrappedComponent: React.ComponentType<Props> | React.ElementType<Props>,
```

To answer your question about why we need `ElementType` – it's just for the sake of comprehensiveness. See the type def:

```ts
type ElementType<P = any> =
  {
      [K in keyof JSX.IntrinsicElements]: P extends JSX.IntrinsicElements[K] ? K : never
  }[keyof JSX.IntrinsicElements] |
  ComponentType<P>;
```

**Review by isaachinman — CHANGES_REQUESTED** [review]

File: src/appWithTranslation.tsx (hunk 1 above)
Comment (petarvujovic98) [reply src/appWithTranslation.tsx:21]: The reason that I asked in the first place is because of the following error when providing ElementType with a generic type parameter like `Props` in our case
Screenshot_10-11-2021_19:11:20
Screenshot_10-11-2021_19:09:49

Comment (isaachinman) [reply src/appWithTranslation.tsx:21]: OK, I'm fine with just using `React.ComponentType<Props>`, but we'll need to wait for the v9 release to publish a change like that (should be this week).

If you're happy with that, please change the target of your PR to: https://github.com/isaachinman/next-i18next/pull/1512

Comment (petarvujovic98) [reply src/appWithTranslation.tsx]: I don't have any problem with that

**Review by isaachinman — APPROVED** [review]
