### PR TITLE
fix: Setting stackTraceLimit properly in createConsoleLog

### LINKED ISSUE #550: Error.stackTraceLimit not being reset if strictMode is off
## Describe the bug
createConsoleLog function in src/utils/console-message.ts sets Error.stackTraceLimit and returns before it can be set back to previous value if strictMode is false.

This breaks our build process.

## Occurs in next-i18next version
v2.0.0

## Expected behaviour
Error.stackTraceLimit is not being set before we check for strictMode value

### PR DESCRIPTION
**Pull request by jakubjanousek**
fixes #550

### CODE REVIEW

File: src/utils/console-message.ts [hunk 1]
```diff
@@ -52,7 +51,7 @@ export default function createConsoleLog(messageType, message) {
 
   /* Temporarily set the stacktrace to 0 or errorStackTraceLimit,
      in order to only display a message */
-  (Error as any).errorStackTraceLimit = errorStackTraceLimit
+  Error.stackTraceLimit = errorStackTraceLimit
```
Comment (isaachinman) [inline src/utils/console-message.ts]: Why was this changed?

Comment (jakubjanousek) [reply src/utils/console-message.ts]: I have removed 2 lines
39: set Error.stackTraceLimit, but did it before check for strictMode
55: didn't do anything as far as I know, since there is no property errorStackTraceLimit on Error (hence there needed to be `as any`)

I have replaced them by line 54, which sets Error.stackTraceLimit at the correct place
