### PR TITLE
fix(bug): update lng query param on subpath change

### LINKED ISSUE #504: lng query param is wrong when on secondary language
## Describe the bug
When loading a secondary lang page, the attached `lng` query string param is the **default** one.

``` 
// My config
{
  browserLanguageDetection: false,
  serverLanguageDetection: false,
  defaultLanguage: 'en',
  otherLanguages: ['de'],
  localeSubpaths: {
    de: 'de',
  }
}
```
## Occurs in next-i18next version
v1.2.0

## Steps to reproduce
Navigate to `/de/hello-world` page.
Check the `lng` query parameter value, it will `en` instead of **de**.

## Expected behaviour
The `lng` query parameter should reflect a proper lng value.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

## Additional context
Go to see the issue
https://pknpq.sse.codesandbox.io/de/about

https://codesandbox.io/s/next-i18next-issue-wrong-query-pknpq

### PR DESCRIPTION
**Pull request by felixmosh**
This PR fixes #504 bug

### CODE REVIEW

File: src/middlewares/next-i18next-middleware.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export default function (nexti18next) {
         subpathIsPresent(req.url, subpathFromLng(config, l)))
 
       if (lngFromCurrentSubpath !== undefined && lngFromCurrentSubpath !== currentLng) {
-
+        currentLng = lngFromCurrentSubpath
```
Comment (isaachinman) [inline src/middlewares/next-i18next-middleware.ts]: Can we achieve the same thing by just referencing `req.i18n.language` below instead of putting `currentLng` into the query?

Comment (felixmosh) [reply src/middlewares/next-i18next-middleware.ts]: I changed the value because the assignment occurs here  https://github.com/isaachinman/next-i18next/blob/e6d70129a43012e0e503f51af28ed47f7bf5adb4/src/middlewares/next-i18next-middleware.ts#L85

Comment (isaachinman) [reply src/middlewares/next-i18next-middleware.ts]: Yes I know, I'm asking if it's possible to get the language from `req.i18n` instead.

Comment (isaachinman) [reply src/middlewares/next-i18next-middleware.ts]: Not sure we are understanding each other. I can take a look later, this does appear to fix a bug in the short term.

Can you please just move this new line below the `req.i18n.changeLanguage` line. Thanks!

Comment (felixmosh) [reply src/middlewares/next-i18next-middleware.ts]: Done

**Comment by felixmosh** [comment]
please tag me whenever you change this code, I would like to learn :]

**Comment by felixmosh** [comment]
When it will be published?

**Comment by isaachinman** [comment]
v1.2.1.
