### PR TITLE
fix: TS issues for v8-beta

### LINKED ISSUE #907: Missing types in 8.0.0-beta
## Describe the bug
I tried out the new beta release that integrates with Next's new i18n internationalization features. It works all very nicely, thanks for the fast development towards this new release. There is only one thing that holds me back from deploying it Vercel. 
When importing `{appWithTranslation}` or `{useTranslation}` from 'next-i18next' in any typescript file (e.g. `_app.tsx`) I get the warning `'"../node_modules/next-i18next/types"' has no exported member named 'appWithTranslation'. Did you mean 'AppWithTranslation'?` 
It seems like there are missing exports in that `types.d.ts`. While the local server still works, the build process to Vercel fails.

## Occurs in next-i18next version
8.0.0-beta.0

## Steps to reproduce
Clone the demo repo at https://github.com/isaachinman/next-i18next-vercel and simply change the file extension of `pages/_app.js` to `pages/_app.tsx`. The import warning will then be displayed.

## Expected behaviour
Correct type definitions.

### PR DESCRIPTION
**Pull request by franzmoro**
- fixes #907 by exposing `appWithTranslation` type
- changes `appWithTranslation` type signature: param is a React Component, not a React Component instance
~~- adds a Next.js example to typescript~~
- fixes the `run-example:prod` script by adding the `build` step before it

### CODE REVIEW

**Comment by nclsndr** [comment]
thx @franzmoro I was about to open one!

File: types.d.ts [hunk 1]
```diff
@@ -71,7 +73,6 @@ declare class NextI18Next {
   config: Config
   useTranslation: UseTranslation
   withTranslation: WithTranslationHocType
-  appWithTranslation: AppWithTranslation
 }
 
 export default NextI18Next
```
Comment (nclsndr) [inline types.d.ts:78]: I guess all the following part is outdated since the package does not export `NextI18Next` class anymore.

```typescript
declare class NextI18Next {
  constructor(config: InitConfig);
  Trans: Trans
  i18n: I18n
  initPromise: InitPromise
  config: Config
  useTranslation: UseTranslation
  withTranslation: WithTranslationHocType
  appWithTranslation: AppWithTranslation
}

export default NextI18Next
```

**Review by nclsndr — COMMENTED** [review]
[disclaimer] I'm not a regular contributor to this lib
Just giving my review since I was doing the same ^^ 
thx again @franzmoro for the great work

File: examples/with-typescript/tsconfig.json [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+  "compilerOptions": {
+    "target": "es5",
+    "lib": [
+      "dom",
+      "dom.iterable",
+      "esnext"
+    ],
+    "allowJs": true,
+    "skipLibCheck": true,
+    "strict": false,
```
[the remark this answers is not in the document]
Comment (franzmoro) [reply examples/with-typescript/tsconfig.json:11]: This file is the default `tsconfig.json` created when running `yarn dev` straight after having created the Next.js app with `npx create-next-app`. The reason is presumably to get an app started more quickly.

I guess it could be up to the dev(s) to configure the `strict` and `allowJs` options.

File: examples/with-typescript/tsconfig.json [hunk 3]
```diff
@@ -0,0 +1,29 @@
+{
+  "compilerOptions": {
+    "target": "es5",
+    "lib": [
+      "dom",
+      "dom.iterable",
+      "esnext"
+    ],
+    "allowJs": true,
```
[the remark this answers is not in the document]
Comment (franzmoro) [reply examples/with-typescript/tsconfig.json:9]: See [above comment](https://github.com/isaachinman/next-i18next/pull/922#discussion_r565569121) about default `tsconfig.json` and letting the dev(s) decide.

File: types.d.ts (hunk 1 above)
Comment (franzmoro) [reply types.d.ts]: thanks @nclsndr! removed in 7e6e8e2

File: types.d.ts [hunk 4]
```diff
@@ -59,19 +60,7 @@ export type SSRConfig = {
...
-  i18n: I18n
-  initPromise: InitPromise
-  config: Config
-  useTranslation: UseTranslation
-  withTranslation: WithTranslationHocType
-  appWithTranslation: AppWithTranslation
-}
-
-export default NextI18Next
+}
```
Comment (isaachinman) [inline types.d.ts:66]: Please add a new line to end of files.

**Review by isaachinman — COMMENTED** [review]
Hey @franzmoro this looks great, thanks! However, can we split the actual type changes and the `with-typescript` example into two PRs, and review them sequentially?

File: types.d.ts (hunk 4 above)
Comment (franzmoro) [reply types.d.ts:66]: what if we add prettier in a separate PR? it would be better than manually have to do that.

Comment (isaachinman) [reply types.d.ts:66]: I don't think prettier should be necessary – eslint should be able to achieve whatever you like. But yes, that should be a separate PR as well. Thanks!

**Comment by franzmoro** [comment]
@isaachinman addressed [your comment](https://github.com/isaachinman/next-i18next/pull/922#pullrequestreview-578249130), and removed the typescript example from this PR.

I will open another one for it.

**Comment by felixmosh** [comment]
Why all the work (and bugs) around TS types?
Typescript is great with generation of types out of TS source code, so why we don't use it?
I love using [TSDX](https://github.com/formium/tsdx) in all of my TS projects since it "just" solves most of the TS configs & many more features, such as `esm` & `cjs` versions, `dev` & `prod`  versions, types export, github actions config for tests.

What do you think about start using it?

**Comment by isaachinman** [comment]
@felixmosh Using a tool to automatically generate exported types sounds great. I've never used `tsdx`, but my main concern would be browser targeting – `cjs` is fine, but what is the browser target? Would you be willing to create a POC PR?

File: package.json [hunk 5]
```diff
@@ -35,7 +35,7 @@
     "build:examples/simple": "yarn --cwd examples/simple && yarn --cwd examples/simple build",
     "prepublishOnly": "yarn build",
     "run-example": "yarn build && cd examples/simple && yarn && yarn dev",
-    "run-example:prod": "yarn --cwd examples/simple start",
+    "run-example:prod": "yarn build:examples/simple && yarn --cwd examples/simple start",
```
Comment (isaachinman) [inline package.json:38]: Hey, not sure this change belongs in this PR? Can you explain your reasoning?

**Comment by felixmosh** [comment]
> @felixmosh Using a tool to automatically generate exported types sounds great. I've never used `tsdx`, but my main concern would be browser targeting – `cjs` is fine, but what is the browser target? Would you be willing to create a POC PR?

I will try :]

File: package.json (hunk 5 above)
Comment (franzmoro) [reply package.json:38]: reasoning: running this script in current version fails.

Comment (franzmoro) [reply package.json:38]: if you prefer to leave it broken, let me know 😬

Comment (franzmoro) [reply package.json:38]: i can put this in a separate PR if that helps

Comment (isaachinman) [reply package.json:38]: This command was previously used in e2e tests, and `yarn build` was omitted intentionally, to prevent unnecessary rebuilds during the CI process. I suppose this is fine to leave in for now, until we revamp e2e tests.

**Review by isaachinman — APPROVED** [review]

**Comment by felixmosh** [comment]
@isaachinman, i've tried to migrate to tsdx, apparently, it doesn't supports multiple entry points (index & serverSideTranslations).
Dumping the idea for now...

**Comment by isaachinman** [comment]
OK, thanks for investigating!

**Comment by TKone7** [comment]
Thank you very much for this work. Do I see it correctly that the  `Trans` type is still not correctly exported? I receive "'Trans' only refers to a type, but is being used as a value here.ts(2693)" when using `<Trans />` tag in my code.
